HotelReservationSystem/Models/Hotel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace HotelReservationSystem.Models
{
    public class Hotel
    {
        public int Id { get; set; }

        [Display(Name = "Hotel Name")]
        public string Name { get; set; }

        public string Description { get; set; } 

        public string Image { get; set; }

        public string Email { get; set; }

        [Display(Name = "Contact No")]
        public string Contact { get; set; }

        [Display(Name = "Road Address")] 
        public string RoadAddress { get; set; }

        public Nullable<int> AreaId { get; set; }

        public virtual Area Area { get; set; }

        public Nullable<int> DistrictId { get; set; }

        public virtual District District { get; set; }

        public Nullable<int> DivisionId { get; set; }

        public virtual Division Division { get; set; }

        public Nullable<int> HotelRatingId { get; set; }

        public virtual HotelRating HotelRating { get; set; }

        public string HotelAmenities { get; set; }

        public virtual HotelAmenity HotelAmenity { get; set; }

        public string Password { get; set; }

        public Nullable<int> ActorId { get; set; }

        public virtual Actor Actor { get; set; }

        public Nullable<bool> Status { get; set; }

        [Display(Name = "Joining Date")]
        public Nullable<DateTime> JoinDate { get; set; }

        [Display(Name = "Last Edit")]
        public Nullable<DateTime> EditDate { get; set; }

        public virtual ICollection<HotelAccount> HotelAccounts { get; set; }

        public virtual ICollection<Room> Rooms { get; set; }


        [NotMapped] 
        public IEnumerable<HotelAmenity> HotelAmenityIds { get; set; }

        [NotMapped]
        public string[] HotelAmenityIdsArray { get; set; }

        [NotMapped]
        public IEnumerable<HotelRating> HotelRatingIds { get; set; }


        [NotMapped]
        public IEnumerable<Division> DivisionIds { get; set; }

        [NotMapped]
        public IEnumerable<District> DistrictIds { get; set; }

        [NotMapped]
        public IEnumerable<Area> AreaIds { get; set; }
        
    }
}

HotelReservationSystem/Controllers/HotelController.cs
using HotelReservationSystem.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace HotelReservationSystem.Controllers
{
    public class HotelController : Controller
    {
        private DatabaseContext db = new DatabaseContext();

        //GET: HotelAccount
        public ActionResult AccountList()
        {
            return View(db.HotelAccount.ToList());
        }

        //GET: HotelAccount/Create
        public ActionResult AccountListPartial()
        {
            HotelAccount hotelAccount = new HotelAccount();
            using (DatabaseContext db = new DatabaseContext())
            {
                hotelAccount.PaymentMethodIds = db.PaymentMethod.ToList();
            }

            return View(hotelAccount);
        }

        //POST: HotelAccount/Create
        public ActionResult CreateHotelAccount(HotelAccount hotelAccount)
        {
            hotelAccount.EditDate = @DateTime.Now;
            hotelAccount.HotelId = 1;           

            if (ModelState.IsValid)
            {
                db.HotelAccount.Add(hotelAccount);
                db.SaveChanges();
                return RedirectToAction("AccountList");
            }

            return View(hotelAccount);
        }

        //GET: HotelAccount/Edit/1
        public ActionResult EditHotelAccount(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HotelAccount hotelAccount = db.HotelAccount.Find(id);
            if (hotelAccount == null)
            {
                return HttpNotFound();
            }
            return View(hotelAccount);
        }

        //POST: HotelAccount/Edit/1
        [HttpPost]
        public ActionResult EditHotelAccount(HotelAccount hotelAccount)
        {
            //admin.JoinDate = @DateTime.Now;
            hotelAccount.EditDate = DateTime.Now;
            hotelAccount.HotelId = 1;

            if (ModelState.IsValid)
            {
                db.Entry(hotelAccount).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("AccountList");
            }
            return View(hotelAccount);
        }

        //GET: HotelAccount/Delete/1
        public ActionResult DeleteHotelAccount(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HotelAccount hotelAccount = db.HotelAccount.Find(id);
            if (hotelAccount == null)
            {
                return HttpNotFound();
            }
            return View(hotelAccount);
        }

        //POST: HotelAccount/Delete/1
        [HttpPost]
        public ActionResult DeleteHotelAccount(int id)
        {
            HotelAccount hotelAccount = db.HotelAccount.Find(id);
            db.HotelAccount.Remove(hotelAccount);
            db.SaveChanges();
            return RedirectToAction("AccountList");
        }
    
        //View Confirm Reservation
        public ActionResult ConfirmReservation()
        {
            return View(db.Reservation.ToList());
        }

        //GET: Hotel
        public ActionResult HotelDashboard()
        {
            var test = db.Hotel.FirstOrDefault();

            Hotel model = new Hotel
            {
                Id = test.Id,
                Name = test.Name,
                Description = test.Description,
                Image = test.Image,
                Contact = test.Contact,
                Email = test.Email,
                RoadAddress = test.RoadAddress,
                AreaId = test.AreaId,
                DistrictId = test.DistrictId,
                DivisionId = test.DivisionId,
                HotelRatingId = test.HotelRatingId,
                HotelAmenities = test.HotelAmenities,
                Password = test.Password,
                ActorId = test.ActorId,
                Status = test.Status,
                JoinDate = test.JoinDate,
                EditDate = test.EditDate
            };
            using (DatabaseContext db = new DatabaseContext())
            {

                //model.HotelAmenityIdsArray = model.HotelAmenities.Split(',').ToArray();

                model.HotelAmenityIds = db.HotelAmenity.ToList();
                model.HotelRatingIds = db.HotelRating.ToList();
                model.DivisionIds = db.Division.ToList();
                model.DistrictIds = db.District.ToList();
                model.AreaIds = db.Area.ToList();
            }

            return View(model);
        }

        //POST: Hotel/Details/1
        [HttpPost]
        public ActionResult HotelDashboard(Hotel hotel)
        {
            var data = db.Hotel.Where(x => x.Email == hotel.Email && x.Password == hotel.Password).FirstOrDefault();
            if (data == null)
            {
                return RedirectToAction("Index");
            }
            else
            {
                //data.HotelAmenityIdsArray = data.HotelAmenities.Split(',').ToArray();
                Session["Id"] = hotel.Id;
                Session["Email"] = hotel.Email;
                return View(data);
            }
            //return View();
        }

        //GET: Hotel/Edit/1
        public ActionResult EditHotel(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Hotel user = db.Hotel.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        //POST: Hotel/Edit/1
        [HttpPost]
        public ActionResult EditHotel(Hotel hotel, HttpPostedFileBase Image)
        {
            //admin.JoinDate = @DateTime.Now;
            hotel.EditDate = DateTime.Now;

            //if (Image.ContentLength > 0)
            if (Image != null)
            {
                string fileName = Path.GetFileNameWithoutExtension(Image.FileName);
                string extension = Path.GetExtension(Image.FileName);
                fileName = DateTime.Now.ToString("yymmssfff") + fileName + extension;
                hotel.Image = "~/Images/" + fileName;
                string path = Path.Combine(Server.MapPath("~/Images/"), fileName);
                Image.SaveAs(path);
            }
            hotel.HotelAmenities = string.Join(",", hotel.HotelAmenityIdsArray);
            if (ModelState.IsValid)
            {
                db.Entry(hotel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("HotelDashboard");
            }
            return View(hotel);
        }

        // GET: Hotel
        public ActionResult Index()
        {
            return View();
        }


        //GET: Reservation
        public ActionResult ReservationList()
        {
            return View(db.Reservation.ToList());
        }

        //GET: Reservation/Delete/1
        public ActionResult DeleteReservation(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reservation reservation = db.Reservation.Find(id);
            if (reservation == null)
            {
                return HttpNotFound();
            }
            return View(reservation);
        }

        //POST: Reservation/Delete/1
        [HttpPost]
        public ActionResult DeleteReservation(int id)
        {
            Reservation reservation = db.Reservation.Find(id);
            db.Reservation.Remove(reservation);
            db.SaveChanges();
            return RedirectToAction("ReservationList");
        }

        //GET: Room
        public ActionResult RoomList()
        {
            return View(db.Room.ToList());
        }
        
        public ActionResult RoomListPartial() 
        {
            Room room = new Room();
            using (DatabaseContext db = new DatabaseContext())
            {
                room.RoomTypeIds = db.RoomType.ToList();
                room.RoomAmenityIds = db.RoomAmenity.ToList();
            }

            return View(room);
        }

        //POST: Room/Create
        public ActionResult CreateRoom( Room room, HttpPostedFileBase Image)
        {
            room.EditDate = @DateTime.Now;
            room.HotelId = 1;
            if (Image.ContentLength > 0)
            {
                string fileName = Path.GetFileNameWithoutExtension(Image.FileName);
                string extension = Path.GetExtension(Image.FileName);
                fileName = DateTime.Now.ToString("yymmssfff") + fileName + extension;
                room.Image = "~/Images/" + fileName;
                string path = Path.Combine(Server.MapPath("~/Images/"), fileName);
                Image.SaveAs(path);
            }
           
            room.RoomAmenities = string.Join(",", room.RoomAmenityIdsArray);
            room.AvailableRoom = room.TotalRoom;

            if (ModelState.IsValid)
            {
                db.Room.Add(room);
                db.SaveChanges();
                return RedirectToAction("RoomList");
            }

            return View(room);
        }

        //GET: Room/Edit/1
        public ActionResult EditRoom(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Room room = db.Room.Find(id);
            if (room == null)
            {
                return HttpNotFound();
            }
            return View(room);
        }

        //POST: Room/Edit/1
        [HttpPost]
        public ActionResult EditRoom(Room room, HttpPostedFileBase Image)
        {
            //admin.JoinDate = @DateTime.Now;

HotelReservationSystem/Views/Hotel/AccountList.cshtml
@model IEnumerable<HotelReservationSystem.Models.HotelAccount>

@{
    ViewBag.Title = "Hotel Account Information";
}

@{
    Layout = "~/Views/Shared/_hotel-sideNav.cshtml";
}

<div class="admin-heading">

    <!-- Page Headline -->
    <h1>Account Information</h1>

    <!-- List Search Form Start-->
    <form class="serach-form">
        <div class="form-group">
            <div class="col-sm-offset-7 col-sm-3">
                <input type="text" class="form-control" id="Search" placeholder="Search">
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-2">
                <input type="submit" class="form-control search-btn" id="submit" placeholder="Search" value="Search">
            </div>
        </div>
    </form>
    <!-- List Search Form End-->
    <!-- Add New Button -->
    <button class="btn btn-primary" data-toggle="modal" data-target=".accountInfo-modal"><i class="fas fa-plus-circle"></i> &nbsp;<b>New Account Information</b></button>
</div>

<!-- Partial Account Modal Start -->
@Html.Action("AccountListPartial", "Hotel")

<!-- Account Info List Table Start -->
<div class="table-responsive-md">
    <table class="table table-hover">
        <thead class="admin-table-head">
            <tr>
                <th>Id</th>
                <th>Payment Method</th>
                <th>Account No</th>
                <th>Last Edit</th>
                <th> </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td class="showDetails pointer">@item.Id</td>
                    <td class="showDetails pointer">
                        @if (@item.PaymentMethodId == 0)
                        {
                            <p>No Payment Method</p>
                        }
                        else
                        {
                            <p>@item.PaymentMethod.Method</p>
                        }
                    </td>
                    <td class="showDetails pointer">
                        @if (@item.AccountNo == null)
                        {
                            <p>No Account Number</p>
                        }
                        else
                        {
                            <p>@item.AccountNo</p>
                        }
                    </td>
                    <td class="showDetails pointer">
                        @if (@item.EditDate == null)
                        {
                            <p>No Date</p>
                        }
                        else
                        {
                            <p>@item.EditDate.Value.ToString("dd-MMM-yyyy")</p>
                        }
                    </td>

                    <td>
                        <button type="button" class="btn btn-primary btn-sm open-dialog" data-toggle="modal" data-target="#Update" data-id="@item.Id"><span class="glyphicon glyphicon-edit" style="vertical-align:middle;margin-top: -5px"></span> Edit</button>
                        <button type="button" class="btn btn-danger btn-sm openDiag" data-toggle="modal" data-target="#Delete" data-id="@item.Id"><span class="glyphicon glyphicon-trash" style="vertical-align:middle;margin-top: -5px"></span> Delete</button>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
<!-- Account Info List Table End -->
<!-- Delete Modal Start -->
<div class="modal fade" id="Delete" role="dialog">
    <div class="modal-dialog">

        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Delete</h4>

            </div>

            <div class="modal-body">
                <p><h3>Are you sure you want to delete this?</h3></p>

            </div>
            <div class="modal-footer">
                <form method="post" action="/Hotel/DeleteHotelAccount">
                    <div class="form-group">
                        <label for="Name">Id</label>
                        <input type="text" readonly="readonly" name="Id" id="Id" class="form-control">
                    </div>
                    <button type="submit" class="btn btn-danger">Delete</button>
                    <button class="btn" data-dismiss="modal">No</button>
                </form>
            </div>
        </div>
    </div>
</div>
<!-- Delete Modal end -->

HotelReservationSystem/Views/Hotel/AccountListPartial.cshtml
@model HotelReservationSystem.Models.HotelAccount


<!-- Account Info Modal Start -->
<div class="modal fade accountInfo-modal" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body">
                <div class="row">


                    <div class="col-md-12 modal-form">
                        <h1><b>Add Account Information</b></h1>

                        <form method="post" action="/Hotel/CreateHotelAccount">
                            <div class="form-group">
                                <label for="exampleFormControlSelect1">Payment Method</label>
                                <div style="width:100%">
                                    @Html.DropDownListFor(model => model.PaymentMethodId, new SelectList(Model.PaymentMethodIds, "Id", "Method"), new { id = "normalDropdown" })
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="Name">Account No</label>
                                <input type="number" class="form-control" name="AccountNo" placeholder="Enter No">
                            </div>

                            <div class="form-group">
                                <input type="submit" class="form-control btn-primary" value="Add">
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Account Info Modal End -->
<!-- Account Info Edit Modal Start -->
<div class="modal fade accountInfo-edit-modal" id="Update" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body">
                <div class="row">


                    <div class="col-md-12 modal-form">
                        <h1><b>Edit Account Information</b></h1>

                        <form method="post" action="/Hotel/EditHotelAccount">
                            <div class="form-group">
                                <label for="Name">Id</label>
                                <input type="text" readonly="readonly" name="Id" id="Id" class="form-control">
                            </div>

                            <div class="form-group">
                                <label for="exampleFormControlSelect1">Payment Method</label>
                                <div style="width:100%">
                                    @Html.DropDownListFor(model => model.PaymentMethodId, new SelectList(Model.PaymentMethodIds, "Id", "Method"), new { id = "normalDropdown" })
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="Name">Account No</label>
                                <input type="number" class="form-control" name="AccountNo" placeholder="Enter No">
                            </div>

                            <div class="form-group">
                                <input type="submit" class="form-control btn-primary" value="Add">
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Account Info Edit Modal End -->

@section scripts{
    <script>
        $(function () {
            $("#normalDropdown").chosen({
                width: "100%"
            });
        });
    </script>
}

HotelReservationSystem/Views/Hotel/RoomList.cshtml
@model IEnumerable<HotelReservationSystem.Models.Room>

@{
    ViewBag.Title = "Room List";
}

@{
    Layout = "~/Views/Shared/_hotel-sideNav.cshtml";
}

<div class="admin-heading">

    <!-- Page Headline -->
    <h1>Room List</h1>

    <!-- List Search Form Start-->
    <form class="serach-form">
        <div class="form-group">
            <div class="col-sm-offset-7 col-sm-3">
                <input type="text" class="form-control" id="Search" placeholder="Search">
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-2">
                <input type="submit" class="form-control search-btn" id="submit" placeholder="Search" value="Search">
            </div>
        </div>
    </form>
    <!-- List Search Form End-->
    <!-- Add New Button -->
    <button class="btn btn-primary" data-toggle="modal" data-target=".room-modal"><i class="fas fa-plus-circle"></i> &nbsp;<b>New Room</b></button>
</div>

<!-- Partial Room Modal Start -->
@Html.Action("RoomListPartial", "Hotel")

<!-- Room List Table Start -->
<div class="table-responsive-md">
    <table class="table table-hover">
        <thead class="admin-table-head">
            <tr>
                <th>Id</th>
                <th>Hotel</th>
                <th>Description</th>
                <th>Image</th>
                <th>Room Type</th>
                <th>Total Room</th>
                <th>Available Room</th>
                <th>Room Amenities</th>
                <th>Price</th>
                <th>Last Edit</th>
                <th> </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td class="showDetails pointer">@item.Id</td>
                    <td class="showDetails pointer">
                        @if (@item.HotelId == null)
                        {
                            <p>No Hotel</p>
                        }
                        else
                        {
                            <p>@item.Hotel.Name</p>
                        }
                    </td>

                    <td class="showDetails pointer">
                        @if (@item.Description == null)
                        {
                            <p>No Description</p>
                        }
                        else
                        {
                            <p>@item.Description</p>
                        }
                    </td>
                    <td class="showDetails pointer">

                        @if (@item.Image == null)
                        {
                            <img src="~/Images/no-image-found.jpg" style="width:100px;" />
                        }
                        else
                        {
                            <img src="@Url.Content(@item.Image)" style="width:100px;" />
                        }
                    </td>
                    <td class="showDetails pointer">
                        @if (@item.RoomTypeId == null)
                        {
                            <p>No Room Types</p>
                        }
                        else
                        {
                            <p>@item.RoomType.Name</p>
                        }
                    </td>
                    <td class="showDetails pointer">
                        @if (@item.TotalRoom == null)
                        {
                            <p>No Room Types</p>
                        }
                        else
                        {
                            <p>@item.TotalRoom</p>
                        }
                    </td>
                    <td class="showDetails pointer">
                        @if (@item.AvailableRoom == null)
                        {
                            <p>No Room Types</p>
                        }
                        else
                        {
                            <p>@item.AvailableRoom</p>
                        }
                    </td>
                    <td class="showDetails pointer">
                        @if (@item.RoomAmenities == null)
                        {
                            <p>No Room Amenities</p>
                        }
                        else
                        {
                            <p>@item.RoomAmenities</p>
                        }
                    </td>
                    <td class="showDetails pointer">
                        @if (@item.Price == 0)
                        {
                            <p>No Price</p>
                        }
                        else
                        {
                            <p>@item.Price</p>
                        }
                    </td>
                    <td class="showDetails pointer">
                        @if (@item.EditDate == null)
                        {
                            <p>No Date</p>
                        }
                        else
                        {
                            <p>@item.EditDate.Value.ToString("dd-MMM-yyyy")</p>
                        }
                    </td>
                    <td>
                        <button type="button" class="btn btn-primary btn-sm open-dialog" data-toggle="modal" data-target="#Update" data-id="@item.Id"><span class="glyphicon glyphicon-edit" style="vertical-align:middle;margin-top: -5px"></span> Edit</button>
                        <button type="button" class="btn btn-danger btn-sm openDiag" data-toggle="modal" data-target="#Delete" data-id="@item.Id"><span class="glyphicon glyphicon-trash" style="vertical-align:middle;margin-top: -5px"></span> Delete</button>

                        @if (item.Status == true)
                        {
                            <button type="button" class="btn btn-primary btn-sm openDiag" data-toggle="modal" data-target="#Block" data-id="@item.Id"><span class="glyphicon glyphicon-ban-circle" style="vertical-align:middle;margin-top: -5px"></span> Block</button>
                        }
                        else
                        {
                            <button type="button" class="btn btn-danger btn-sm openDiag" data-toggle="modal" data-target="#Unblock" data-id="@item.Id"><span class="glyphicon glyphicon-ok-circle" style="vertical-align:middle;margin-top: -5px"></span> Unblock</button>
                        }
                    </td>
                </tr>

            }
        </tbody>
    </table>
</div>
<!-- Room List Table End -->
<!-- Delete Modal Start -->
<div class="modal fade" id="Delete" role="dialog">
    <div class="modal-dialog">

        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Delete</h4>

            </div>

            <div class="modal-body">
                <p><h3>Are you sure you want to delete this?</h3></p>

            </div>
            <div class="modal-footer">
                <form method="post" action="/Hotel/DeleteRoom">
                    <div class="form-group">
                        <label for="Name">Id</label>
                        <input type="text" readonly="readonly" name="Id" id="Id" class="form-control">
                    </div>
                    <button type="submit" class="btn btn-danger">Delete</button>
                    <button class="btn" data-dismiss="modal">No</button>
                </form>
            </div>
        </div>
    </div>
</div>
<!-- Delete Modal end -->
<!-- Block Modal Start -->
<div class="modal fade" id="Block" role="dialog">
    <div class="modal-dialog">

        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Block</h4>

            </div>

            <div class="modal-body">
                <p><h3>Are you sure you want to block this?</h3></p>

            </div>
            <div class="modal-footer">
                <form method="post" action="/Hotel/BlockRoom">
                    <div class="form-group">
                        <label for="Name">Id</label>
                        <input type="text" readonly="readonly" name="Id" id="Id" class="form-control">
                    </div>
                    <button type="submit" class="btn btn-primary">Block</button>
                    <button class="btn" data-dismiss="modal">No</button>
                </form>
            </div>
        </div>
    </div>
</div>
<!-- Block Modal end -->
<!-- Unblock Modal Start -->
<div class="modal fade" id="Unblock" role="dialog">
    <div class="modal-dialog">

        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Unblock</h4>

            </div>

            <div class="modal-body">
                <p><h3>Are you sure you want to unblock this?</h3></p>

            </div>
            <div class="modal-footer">
                <form method="post" action="/Hotel/UnblockRoom">
                    <div class="form-group">
                        <label for="Name">Id</label>
                        <input type="text" readonly="readonly" name="Id" id="Id" class="form-control">
                    </div>
                    <button type="submit" class="btn btn-primary">Unblock</button>
                    <button class="btn" data-dismiss="modal">No</button>
                </form>
            </div>
        </div>
    </div>
</div>
<!-- Unblock Modal end -->

@section scripts{
    <script>
        $(function () {
            $("#normalDropdown").chosen({
                width: "100%"
            });
        });
    </script>

    <script>
        $(function () {
            $("#multiSelectDropdown").chosen({
                width: "100%"
            });
        });
    </script>
}